### ISSUE TITLE
manage table not in ddl?

### ISSUE THREAD

**Issue by chrisroederucdenver** [jhu-bids/TermHub#226]
Serves me right for working out of the develop branch....

```
(venv) roederc@amc-chais-MacBook-Pro-3 TermHub % python backend/db/initialize.py 
Empty DataFrame
Columns: []
Index: []
INFO: n3c.code_sets does not not exist; will create it
INFO: 
loading n3c.code_sets into postgresql:termhub
Traceback (most recent call last):
  File "/Users/roederc/work/git_bids/TermHub/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/roederc/work/git_bids/TermHub/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "manage" does not exist
LINE 1: INSERT INTO manage (key, value) VALUES ("last_updated_code_s...
```

**Comment by joeflack4** [comment]
Hey Chris, Yeah you are right. We are in the middle of refactoring `sql.ddl` to be produced from a Jinja template, and also this `manage` table is also brand new and needs to be added to that as well.

It's on my radar but this will help me to prioritize it. I'll try and see if I can do this by Monday.

**Comment by joeflack4** [comment]
@chrisroederucdenver I just added creation of this during initialize to `develop`. Do a pull and let me know if this still causes an issue.

**Comment by chrisroederucdenver** [comment]
**Does not need fixed immediately.**

Something is trying to insert before the initialization gets to the line that creates the manage table.
Steps are basically: 
```  
$ dropdb termhub
$ createdb termhub
$ echo "create schema n3c;" | psql termhub
$ echo "set search_path TO n3c;" | psql termhub
$ python backend/db/initialize.py
```
So there is also a check for existence of the database where it creates it if it doesn't exist, that needs to have the schema creation and search_path setting come after.

**Comment by joeflack4** [comment]
Thanks @chrisroederucdenver This was helpful that you pointed this out today.

The set up process is very close to what you are describing.

The `manage` table was something that was added yesterday. I fixed the `manage` table not existing a few hours ago. Just now finished with the script that refreshes an already existing DB, but it would be good to verify that initializing a fresh DB works as expected.

CC @Sigfried We should double check / unit test that `initialize()` is working as expected on a new DB. @chrisroederucdenver Feel free to rerun from scratch on the latest commit from `develop` as well.

**Comment by chrisroederucdenver** [comment]
I've run the load a few times with the steps above to skip over the problems. It seemed a bit slow, in a way that wouldn't motivate me to test this stuff. I remembered and tried the COPY command with great success. It's made to load CSVs and assumes you don't need the index to deal with uniqueness issues. **It loaded the concept_relationship table in 30 seconds**, whereas initialize.py is still running after 10 minutes.
Fair warning, I haven't compared tables loaded the two ways, but a line count of the file minus the header row is what a select count(*) from the table shows.
```
(venv) roederc@amc-chais-MacBook-Pro-3 TermHub % time cat /Users/roederc/work/git_bids/TermHub/termhub-csets/datasets/prepped_files/concept_relationship.csv | psql -c "copy n3c.concept_relationship from STDIN with (FORMAT csv, HEADER true);"
COPY 16971521
cat   0.04s user 0.56s system 2% cpu 26.335 total
psql -c   3.36s user 1.28s system 17% cpu 26.335 total
(venv) roederc@amc-chais-MacBook-Pro-3 TermHub % psql termhub
psql (14.5)
Type "help" for help.

termhub=# select count(*) from n3c.concept_relationship;
  count   
----------
 16971521
(1 row)

termhub=# 
```

Looks like you can get to this functionality from Python too:
https://stackoverflow.com/questions/13125236/sqlalchemy-psycopg2-and-postgresql-copy

**Comment by joeflack4** [comment]
Not a bad suggestion. Yeah, it takes a heck of a long time. Millions of rows in several different tables. Part of the reason it takes long isn't because it's loading / indexing, but also some transformations that it's doing to create some 'derived' tables, which I think are similar to SQL views. Siggie set that part up. I know that Siggie also tried `COPY`. It was something we tried early on, but I don't remember if it was used to refresh the database w/ newly updated tables (in which case I think the way we have of simply renaming the schema should be even faster / instant), or something else. We were trying different variations of loading from CSV as well.

I think the performance on `initialize()` is not too bad right now. The full DB refresh is not too bad either, since it will (hopefully) run on a GitHub action at night, and performance won't be a huge issue there. The biggest performance increase we're looking to do involves updating our tables with new rows, rather than downloading the full table from the enclave and replacing it with what we currently have. This involves using the `objects` API. We've made some progress with that, but some of it is slowed by the relative newness of that API which is still in development.
