### ISSUE TITLE
Progress Tracking doc

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#459]
Tracking google doc: https://docs.google.com/document/d/1lVmY6PQclYudmbyY1HG6xCqJmYXyUu1e4pn8CAx97aA/edit

Appears in notes tab of the project board

**Comment by joeflack4** [comment]
<img width="438" alt="Screen Shot 2023-07-03 at 5 32 13 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/7b9a06e3-72be-4370-9efb-d088262fba20">
I just added it directly instead of making an issue. Up until I guess very recently it wouldn't say "Draft", though.

If you don't like this though or if you think Siggie would prefer it to be the way you had it before, feel free to revert what I've done.
