### ISSUE TITLE
redundant ddl code and missing ddl code

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#496]
https://github.com/jhu-bids/TermHub/blob/develop/backend/db/ddl-14-concept_relationship_plus.jinja.sql

The file name and contents disagree (create for `concept_relationship_plus` is missing) and the contents are redundant with `ddl-7-concept_ids_by_codeset_id.jinja.sql` and `ddl-8-codeset_ids_by_concept_id.jinja.sql`

I noticed because the data types are weird and I need to change the code, but not sure which version to change. (Fixed the datatypes, twice, in 02db7e6c)

**Comment by joeflack4** [comment]
@Sigfried I believe I just addressed this with: https://github.com/jhu-bids/TermHub/commit/3c68d4df39b2e788a50c1a79731c1f8cffcfaece

(i) deleted redundant file, was the second file w/ module name 'concept_relationship_plus', and its contents also were already covered by other DDL, and it the code was worse / had a bug in it anyway. 
(ii) Renamed some files due to number ordering changing due to deleted file.

From what I could see, the changes you made / those other files for `concept_relationship_plus`, `concept_ids_by_codeset_id`, and `codeset_ids_by_concept_id` all look good.

The title of this issue also says "missing DDL code" but I don't see anything missing; I think you addressed that already.
