### ISSUE TITLE
bug in `upload_new_cset_version_with_concepts()` somewhere: not saving parent version

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#598]
I make a copy of an existing code set version (27371375) and upload it using `upload_new_cset_version_with_concepts` and setting `parent_version_codeset_id` appropriately. It correctly gets uploaded to the enclave:

<img width="618" alt="image" src="https://github.com/jhu-bids/TermHub/assets/1586931/7d130a7e-0ea8-4f5c-aaa0-adbac935fdc2">

but not to the database:

<img width="714" alt="image" src="https://github.com/jhu-bids/TermHub/assets/1586931/940746fa-890c-47f0-a05d-b2f7f92fe9ec">

@joeflack4, can you look at this?

**Comment by joeflack4** [comment]
Sure, I'll take a look at this.

**Comment by joeflack4** [comment]
@Sigfried I took a cursory look at this but before I continue, I just want to get some more clarity.

I walked through using `test_upload_cset_version_from_csv()` and it was as I suspected: `upload_new_cset_version_with_concepts()` uploads to the enclave, but does not also import that same cset version into our database. That would be done via a separate step, such as the DB refresh. Were you thinking the opposite?

That being said, the new cset version you uploaded into the enclave _did_ make its way into our DB by the time you checked. My guess is that between when you uploaded and check, the DB refresh had run on its normal schedule and imported it for you.

I think the problem is that only these fields that show up in this "object model"::"table model" mapping are getting imported into our DB:

`models.py`:
```py
# OMOPConceptSet (Version): object <-> dataset
add_mappings(
    """OMOPConceptSet,            code_sets
       codesetId,                 codeset_id
       createdAt,                 created_at
       conceptSetVersionTitle,    concept_set_version_title
       isMostRecentVersion,       is_most_recent_version
       version,                   version
       createdBy,                 created_by
       conceptSetNameOMOP,        concept_set_name
       intention,                 intention
       updateMessage,             update_message
       atlasJsonResourceUrl,      atlas_json_resource_url
       provenance,                provenance
       sourceApplicationVersion,  source_application_version
       isDraft,                   is_draft
       sourceApplication,         source_application
       limitations,               limitations""")
```

**Probable solution**
`parentVersionId,     parent_version_id` is not an entry. I'm thinking all we need to do to fix this is add it.

---

That being said, I wonder why we didn't map this before? Is this one of
